image: alpine:3.7

services:
  - mysql

stages:
  - deploy
  - save
  - build
  - migrate

cache:
  paths:
    - .apt/

build:
  stage: build
  image: node:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - npm
  before_script:
    - npm install -g heroku
  script:
    - heroku run --app $HEROKU_APP_NAME composer update
    - heroku run --app $HEROKU_APP_NAME composer dump-autoload
  only:
    refs:
      - master

backup:
  image: mysql
  stage: backup
  variables:
    MYSQL_DATABASE: fmzy4o9i0222t5c4
    MYSQL_HOST: g3v9lgqa8h5nq05o.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
    MYSQL_USER: ajmatif7xnvmger6
    MYSQL_PASSWORD: gg258e7refgieg02

  allow_failure: true

  script:
    mysqldump --user=$MYSQL_USER --password=$MYSQL_PASSWORD --host=$MYSQL_HOST $MYSQL_DATABASE &gt; exam_system_backup.sql

  artifacts:
    paths:
      - /db/

deploy:
  stage: deploy
  script:
    - apk update && apk add git
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
  only:
    refs:
      - master

migrate:
  stage: migrate
  image: node:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - npm
  before_script:
    - npm install -g heroku
  script:
    - heroku run --app $HEROKU_APP_NAME php artisan migrate
  only:
    refs:
      - master

save:
  stage: save
  script:
    - apk update && apk add git
    - git push  https://$BITBUCKET_USER:$BITBUCKET_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_USER/$BITBUCKET_APP_NAME.git HEAD:master
  only:
    refs:
      - master
