version: "3"
services:
    web:
        image: webdevops/php-nginx:7.1
        ports:
            - "8082:80"
            # - "8443:443"
        volumes:
            - /c/exam_system:/app
        environment:
            - PHP_DEBUGGER=xdebug
            - PHP_DISPLAY_ERRORS=1
            - PHP_DATE_TIMEZONE=Asia/Ho_Chi_Minh
            - WEB_DOCUMENT_ROOT=/app/public
    database:
        image: mysql:5.7
        volumes:
          - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=exam"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=root"
            - "MYSQL_ROOT_PASSWORD=root"
        ports:
            - "33061:3306"

volumes:
    dbdata: